### ISSUE TITLE
apidiff should not include internal types when InternalsVisibleTo is used

### ISSUE THREAD

**Issue by ejball** [Faithlife/FaithlifeApiDiffTools#1]
The `apidiff` tool currently treats `internal` as `public` when it finds `InternalsVisibleToAttribute`. This was surprising behavior and should be opt-in, IMHO.

**Comment by ddunkin** [comment]
Comparing internal types was important for the initial use case of the tool (PCL Libronix.Utility and its platform-specific sibling assemblies) but you're right, it's not generally useful.
